### ISSUE TITLE
Doesn't work after new OpenAI Cloudflare protections

### ISSUE THREAD

**Issue by Galz648** [RomanHotsiy/commitgpt#22] opened 2022-12-12 10:53 UTC
## Description
Using this cli tool for the first time, posting the session token doesn't work.
* I believe there should be a feature to set it as a local variable as it is easier to debug.
## Steps to Reproduce
* use the tool for the first time (maybe try to delete the existing token if you already used it)
* copy the token from the browser
* paste it into the terminal window

## Expected Behavior
expected the access token to be accepted

## Actual Behavior

I get a "invalid token" message.

## Environment
Darwin 21.6.0

**Comment by gaui** [comment] 2022-12-12 13:40
Same here. I get:

> Invalid token. Please try again.

**Comment by RomanHotsiy** [comment] 2022-12-12 13:57
More details here https://github.com/transitive-bullshit/chatgpt-api#update-december-12-2022 and here https://github.com/transitive-bullshit/chatgpt-api/issues/96

**Comment by sapirgolan** [comment] 2022-12-12 15:42
Duplicate of #21

**Comment by davidlj95** [comment] 2023-01-08 03:56
I managed to workaround the issue by using [`chatgpt` lib](https://github.com/transitive-bullshit/chatgpt-api). It opens a browser window so you can authenticate as usual. And then proceeds to send the diff to get the commit message suggestions. It's a poor man's workaround, as you have to login every time you run the command with the browser. Buut, it's something

Check it out here:
https://github.com/davidlj95/commitgpt/tree/use-chatgpt-lib-with-puppeteer-to-bypass-cloudflare-restrictions

**Comment by amatzen** [comment] 2023-01-21 10:24
Utilizes this repo any ChatGPT-specific feature sets, that are not available in the regular GPT-3 API, or could the possible solution for this issue being a conversion to GPT-3 until ChatGPT is commercially available with a (hopefully) usage-based pricing model?

**Comment by friuns2** [comment] 2023-02-05 19:18
https://github.com/transitive-bullshit/chatgpt-api

Update February 1, 2023
This package no longer requires any browser hacks – it is now using the official OpenAI completions API with a leaked model that ChatGPT uses under the hood. 🔥

**Comment by amatzen** [comment] 2023-03-06 11:26
New paid [ChatGPT API](https://openai.com/blog/introducing-chatgpt-and-whisper-apis) released by @openai. Maybe switch to that instead of any "hacks" or unofficial sources.

**Comment by farhadsoft** [comment] 2023-03-24 21:23
![image](https://user-images.githubusercontent.com/1423681/227644066-a4e16854-5ed6-4dea-948a-a20aa9e5e3bf.png)
Something is wrong: **Invalid token. Please try again.**

**Comment by michael-sumner** [comment] 2023-04-04 10:28
I am also experiencing the same issue `Invalid token. Please try again.`. Has anyone fixed their issue?

**Comment by JeanRessouche** [comment] 2023-04-05 08:49
Same (with GPT paid account) :(

**Comment by hadees** [comment] 2023-04-07 18:20
can't it just us the official api now?

**Comment by lucaszdev** [comment] 2023-04-11 19:15
@RomanHotsiy Fix this please

<img width="1409" alt="Screenshot 2023-04-11 at 16 15 12" src="https://user-images.githubusercontent.com/53530532/231266029-9a0edbb8-f75a-4ca6-a22c-a2149ba67e87.png">

**Comment by RomanHotsiy** [comment] 2023-05-15 00:17
Fixed in 2.0.0 by https://github.com/RomanHotsiy/commitgpt/pull/27

**Closed by RomanHotsiy** 2023-05-15 00:17 UTC
